# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Start_Window(object):
    def setupUi(self, Start_Window):
        Start_Window.setObjectName("Start_Window")
        Start_Window.resize(460, 310)
        self.centralwidget = QtWidgets.QWidget(Start_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.pB_Camera = QtWidgets.QPushButton(self.centralwidget)
        self.pB_Camera.setGeometry(QtCore.QRect(60, 120, 140, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pB_Camera.setFont(font)
        self.pB_Camera.setObjectName("pB_Camera")
        self.pB_Photo = QtWidgets.QPushButton(self.centralwidget)
        self.pB_Photo.setGeometry(QtCore.QRect(260, 120, 140, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pB_Photo.setFont(font)
        self.pB_Photo.setObjectName("pB_Photo")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(120, 40, 221, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        Start_Window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Start_Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 460, 21))
        self.menubar.setObjectName("menubar")
        Start_Window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Start_Window)
        self.statusbar.setObjectName("statusbar")
        Start_Window.setStatusBar(self.statusbar)

        self.retranslateUi(Start_Window)
        QtCore.QMetaObject.connectSlotsByName(Start_Window)

    def retranslateUi(self, Start_Window):
        _translate = QtCore.QCoreApplication.translate
        Start_Window.setWindowTitle(_translate("Start_Window", "Start"))
        self.pB_Camera.setText(_translate("Start_Window", "Камера"))
        self.pB_Photo.setText(_translate("Start_Window", "Фото"))
        self.label1.setText(_translate("Start_Window", "Выберите режим"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Start_Window = QtWidgets.QMainWindow()
    ui = Ui_Start_Window()
    ui.setupUi(Start_Window)
    Start_Window.show()
    sys.exit(app.exec_())
